### ISSUE TITLE
Material science: the physical structure of the atom and its chemical properties

### ISSUE THREAD

**Issue by SicariusNoctis** [SicariusNoctis/eagle-eye-tracker#5]
This issue tracks things needed till a cool looking, resilient, physically present structure is produced.

 - Ordering materials
 - Assembly
 - Painting/design

@byarrow Comment some more items as you see fit.

@naimt What would we need to use SolidWorks for?

**Comment by naimt** [comment]
Use solidworks as a reference for the product assembly (has the rough size guidelines)

**Comment by byarrow** [comment]
Update on this Issue:
- Design has been completed
- Design approved by Gary
- Can Start Assembly next
- Most parts and materials have been acquired, except fasteners and Paint

To paint or not to paint; that is the question. Whether it is nobler to apply a slick coat or to let bare metal protrude with all of its rugged glory and strength
