### ISSUE TITLE
Connection latency/transfer rate tests

### ISSUE THREAD

**Issue by YodaEmbedding** [SicariusNoctis/eagle-eye-tracker#8]
RPi<->PC tests

Here's some example tests (the first one is probably easiest):

- Try sending a bunch of ping message (e.g. "ping1", "ping2", "ping3", ...) and check if they're all received and their avg and max ping.
 - Try to send a bunch of messages over the connection. (e.g., "2018-05-31 14:18:04.495") and see timing difference in date stamps in either direction. Might be worthwhile to sync your PC's clock with an internet server (NIST).
 - Test how much data you can transfer

Be sure to test both WiFi and ~~USB~~ Ethernet.

You can upload your code to this Github repository in a directory called latency-tests. Write down your results here in a graph or table or whatever works.

**Comment by VYUN** [comment]
So I did a really basic test whereby I record the average time to send a message from RPI to PC and get a response for 1000 messages. 

- Wifi took about 9 ms per message
- Ethernet took about 0.8 ms per message

Albeit my wifi is kind of crappy and there may be other factors as well. The difference is quite large though, and a direct connection is definitely the ideal choice for latency and consistency.

**Comment by SicariusNoctis** [comment]
@byarrow We'll probably stick with Ethernet in light of this. :P
